### ISSUE TITLE
Create server with tags

### ISSUE THREAD

**Issue by Bonitas** [UpCloudLtd/upcloud-go-api#102]
'CreateServerRequest' does not support tags. Tags are useful to add some metadata or to organise your cloud resources. 

```func (s *Service) GetServers() (*upcloud.Servers, error)```
Returned servers structs actuallty return tags.

**Comment by Bonitas** [comment]
Okay actually found it. I used an outdated version of this library.

**Comment by Darep** [comment]
Glad you got it figured out! :) Just a quick note on tags: UpCloud uses tags primarily for access control, so do note that if you run into any access control problems, it could be the tags.
