### ISSUE TITLE
Proper vendor inclusion for semver and hashicorp libs

### ISSUE THREAD

**Issue by james-nesbitt** [UpCloudLtd/upcloud-go-api#32]
Since Go 1.6, it is common practice to include dependencies in the repository, in the [vendor path](https://golang.org/cmd/go/#hdr-Vendor_Directories)

We should get the semver and hashicorp libs in vendor.

A low impact proprosal:

Consider using gitsubmodules for the two libs:
```
$/> git submodule add --force https://github.com/hashicorp/go-cleanhttp vendor/github.com/hashicorp/go-cleanhttp
$/> git submodule add --force https://github.com/blang/semver vendor/github.com/blang/semver  
```

This would introduce two changes: 

1. .gitmodules file in the root
2. two new submodule roots in vendor

To use them, when building just make sure that any git actions are --recursive (like git clone.)

**Comment by james-nesbitt** [comment]
Hey Jalle, just getting ahead on this one for an issue that I have: https://github.com/wunderkraut/radi-handler-upcloud/issues/3

**Comment by Jalle19** [comment]
From what I've read it's not recommended to use vendoring for libraries. Has this practice changed or am I just misinformed?

**Comment by Jalle19** [comment]
@james-nesbitt FYI if you're still working on this, the repository has been moved to `UpCloudLtd`

**Comment by PopoSensei** [comment]
Using go.mod since updated to go version 1.13
