### ISSUE TITLE
Support new features and attributes from v1.2.5 and up

### ISSUE THREAD

**Issue by Jalle19** [UpCloudLtd/upcloud-go-api#40]
Firewall rules in particular have gotten some changes, as well as server states

**Comment by LordChocoBlizzBallz** [comment]
Thanks for opening this issue. I did some digging and at least server states have not changed and are the same which are found in server.go

https://developers.upcloud.com/8-servers/#server-states
```	
ServerStateStarted     = "started"
ServerStateStopped     = "stopped"
ServerStateMaintenance = "maintenance"
ServerStateError       = "error"
```	

Same for firewall rules in firewall.go

https://developers.upcloud.com/11-firewall/

```	
	Action                  string `xml:"action"`
	Comment                 string `xml:"comment,omitempty"`
	DestinationAddressStart string `xml:"destination_address_start,omitempty"`
	DestinationAddressEnd   string `xml:"destination_address_end,omitempty"`
	DestinationPortStart    string `xml:"destination_port_start,omitempty"`
	DestinationPortEnd      string `xml:"destination_port_end,omitempty"`
	Direction               string `xml:"direction"`
	Family                  string `xml:"family"`
	ICMPType                string `xml:"icmp_type,omitempty"`
	Position                int    `xml:"position"`
	Protocol                string `xml:"protocol,omitempty"`
	SourceAddressStart      string `xml:"source_address_start,omitempty"`
	SourceAddressEnd        string `xml:"source_address_end,omitempty"`
	SourcePortStart         string `xml:"source_port_start,omitempty"`
	SourcePortEnd           string `xml:"source_port_end,omitempty"`
```	

Could you please be more specific about what has changed and is not supported?

**Comment by Jalle19** [comment]
E.g. https://github.com/UpCloudLtd/upcloud-go-api/blob/master/upcloud/firewall.go#L6 should be removed, apart from that I can't remember.

**Comment by LordChocoBlizzBallz** [comment]
Thanks. Will look into this more thoroughly.

**Comment by PopoSensei** [comment]
This API/SDK has been updated to use UpCloud API v.1.3. There are some features and attributes that aren't supported still, but we will look at those once they are raised up as issues. So any changes and removals should be up to date in new release  once released.
