### ISSUE TITLE
Creating a firewall rule with IP family set to all for drop rule

### ISSUE THREAD

**Issue by ilijamt** [UpCloudLtd/upcloud-go-api#41]
How can I create a firewall rule using the API so I can set the default action to DROP for all.

Currently whenever I try to create it only complains that the family is invalid, in the documentation it says to create this but I cannot create it as Family has to be either IPv4 or IPv6, and cannot be empty as I'm getting if I set it through the front-end.

API Used: **UpCloudLtd/upcloud-go-api@master**

```
&request.CreateFirewallRuleRequest{
			ServerUUID:   uuid,
			FirewallRule: upcloud.FirewallRule {
				Action: upcloud.FirewallRuleActionDrop,
				Direction: upcloud.FirewallRuleDirectionIn,
				Position: 11,
			},
		}
```

The error I'm getting is **The attribute family has an invalid value. (FAMILY_INVALID)**

**Comment by PopoSensei** [comment]
The default rules for Firewall are for now only modified trough the hub. I would suggest just adding 2 rule sets at the end for both of the IP families, if you want to admin those rules trough Go, since the public API accepts that as valid request.
