### ISSUE TITLE
Enabling remote access breaks struct serialization

### ISSUE THREAD

**Issue by ajmyyra** [UpCloudLtd/upcloud-go-api#63]
Hi there,

I noticed that enabling remote access in the API _(VNC console in the control panel)_ seems to completely break JSON serialization for server details, and instead of an error, only an empty struct is returned. Following example works well when remote access is disabled, but enabling it causes the JSON serialization to fail.

```
package main

import (
	"fmt"

	"github.com/UpCloudLtd/upcloud-go-api/upcloud/client"
	"github.com/UpCloudLtd/upcloud-go-api/upcloud/request"
	"github.com/UpCloudLtd/upcloud-go-api/upcloud/service"
)

func main() {
	api := service.New(client.New("username", "password")
	server, err := api.GetServerDetails(&request.GetServerDetailsRequest{UUID: "server_uuid"})
	if err != nil {
		fmt.Println(err)
	}
	fmt.Printf("%+v\n", server)
}
```

I looked at the [relevant code](https://github.com/UpCloudLtd/upcloud-go-api/blob/8ba81055f176aacef4cce3f355aba583a38ce914/upcloud/service/service.go#L139) and error from json.Unmarshal is left unhandled. Thus, no error is returned to the code utilizing GetServerDetails when serialization fails.

Besides this problem, the upgraded API bindings seem amazing and it's been working perfectly for me. Thank you!

**Comment by PopoSensei** [comment]
Added error handling [in this commit](https://github.com/UpCloudLtd/upcloud-go-api/commit/2dc046b8bc7bb0f248e47419c1aed53b2b82317a). Also the underlying type error is being fixed in the main API.
