### ISSUE TITLE
CreateStorageImport should allow passing io.Reader when type is direct_uploud

### ISSUE THREAD

**Issue by aakso** [UpCloudLtd/upcloud-go-api#65]
As opening a file for reading is such a trivial task in Go I feel this should be the default.

Rationale:
user of this library might want to implement a progress bar / status. He/she might also want to calculate a checksum to be compared with the value that UpCloud API returns.

Proposal:
add another public field to CreateStorageImportRequest of type io.Reader or use an internal field with public setter.

**Comment by PopoSensei** [comment]
Issue resolved in #67
